### PR TITLE
TSE Code Review : Project 6 - Building with Responsive Design

### PR DESCRIPTION
**Pull request by simoxsimo**
# [Responsive Design] The New Web website Clone

In this project we've done the following:
- Creating the Layout of the page using CSS Grid and Flexbox.
- Using different breakpoints to create a responsive design by using media queries.

### CODE REVIEW

**Comment by simoxsimo** [comment]
Closed due to linter problem.
Check the fixed pull request [here](https://github.com/simoxsimo/Resposive-Thenextweb-Clone/pull/3)

**Comment by Oluwadamilareolusakin** [comment]
# Hello @simoxsimo and @ClintonEnyinna, your project is spectacular! :rocket:
I haven't seen many will such precision. Your readme is professional, your markup is semantic and your styling is exquisite! There is one small thing that needs addressing before you can merge:

##### Footer
The social icons on the mobile screen size seem to be a bit jumpy. Please give it a second look and your project will shine!

#### Summary
I really love this project :smile:. It is really clean, please keep this energy and level of attention to detail throughout your time at Microverse and beyond! :rocket:. Its been a pleasure reviewing it.

**Review by nikasulo — COMMENTED** [review]
# Hello @simoxsimo and @ClintonEnyinna, your project is spectacular! :rocket:
I haven't seen many with such precision. Your readme is professional, your markup is semantic and your styling is exquisite! There is one small thing that needs addressing before you can merge:

##### Footer
The social icons on the mobile screen size seem to be a bit jumpy. Please give it a second look and your project will shine!

#### Summary
I really love this project :smile:. It is really clean, please keep this energy and level of attention to detail throughout your time at Microverse and beyond! :rocket:. Its been a pleasure reviewing it.

**Comment by simoxsimo** [comment]
@Oluwadamilareolusakin Sorry I didn't see your message.

**Comment by nikasulo** [comment]
That's fine @simoxsimo :+1:. I am going to approve this now but please make the change to the social icons before you merge. I trust you will. Also, look at your navigation on the mobile screen size, you have some sort of margin or padding property on one of the elements causing horizontal scrolling. I am not sure which element it is but I can guess that it's the search icon. Please correct those two before you merge.

Feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilareolusakin) if you need some help :smile:.

**Comment by simoxsimo** [comment]
@Oluwadamilareolusakin Thank you for your trust and I will make sure to fix what you have said.

**Pull request closed without merging**
